# test variables and file
test01: "resources/test01.txt" 
test02: "resources/test02.txt" 
test_out: "test_out.txt" 
test_out_location: "test_out/"

# conda env
conda_env: "../envs/env_MQuad.yaml"
env_R: "../envs/env_testR.yaml"

# Preprocessing
# input directory
dir_input: "/beegfs/scratch/ric.absinta/ric.absinta/pipeline/snakemake_spaceranger_tests_HPC/snakemake_multirun/results/spaceranger/merged/"
# dir_input: "/idle/ric.cosr/ric.cosr/pedrini.edoardo/test_MQuad/data/test_absinta/results/cellranger/merged/"
# dir_input: "/idle/ric.cosr/ric.cosr/pedrini.edoardo/test_MQuad/data/test_Mquad2/results/cellranger/merged/"
dir_standalone: "/idle/ric.cosr/ric.cosr/pedrini.edoardo/test_MQuad/data/test_MQuand/"

# output directory
dir_output: "results/"

# parameters for the run
# chrom: "MT"
# chrom: "chrMT"
chrom: "chrM"

# https://github.com/single-cell-genetics/MQuad
# For droplet-based sequencing data, eg. 10X Chromium CNV, scATAC..etc, it is recommended to add --minDP 5 or a smaller value to prevent errors during fitting. The default value is 10, which is suitable for Smart-seq2 data but might be too stringent for low sequencing depth data.
minDP: 5
test_clones: [2, 3, 4, 5]

# hardcode the sample name:
sample_name:
  # - 'TNBC1'
  # - 'TNBC2'
  # - 'TNBC5'
  # - 'sample_10X_5p'
  # - 's38'
  # - 's59'
  # - 'hBS_RR16_MG'
  # - 'W8_24h_CSF-controls_plus_untreated_multiplexed'
  - MA7678_1
  - MA7678_10
  - MA7678_11
  - MA7678_12
  - MA7678_13
  - MA7678_14
  - MA7678_15
  - MA7678_16
  - MA7678_2
  - MA7678_3
  - MA7678_4
  - MA7678_5
  - MA7678_6
  - MA7678_7
  - MA7678_8
  - MA7678_9
  # - 'SC5v2_Melanoma_5Kcells_Connect_single_channel_gex'
